# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

checksum:
  name_template: "checksums.txt"

docker_digest:
  name_template: "digests.txt"

builds:
  - ldflags: "-s -w"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

docker_signs:
  - ids:
      - dockers_v2
    cmd: cosign
    args:
      - "sign"
      - "--yes"
      - "${artifact}"
    env:
      - COSIGN_YES=true

dockers_v2:
  - id: dockers_v2
    images:
      - 'ghcr.io/{{ envOrDefault "GITHUB_REPOSITORY_OWNER" "cedws" }}/{{ .ProjectName }}'
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      PROJECT_NAME: "{{ .ProjectName }}"
    flags:
      - "--pull"

scoops:
  - skip_upload: '{{ eq (envOrDefault "REPO_VISIBILITY" "private") "private" }}'
    repository:
      name: scoop-bucket
      owner: '{{ envOrDefault "GITHUB_REPOSITORY_OWNER" "cedws" }}'
      token: "{{ .Env.SCOOP_BUCKET_PUSH_TOKEN }}"

homebrew_casks:
  - skip_upload: '{{ eq (envOrDefault "REPO_VISIBILITY" "private") "private" }}'
    repository:
      name: homebrew-tap
      owner: '{{ envOrDefault "GITHUB_REPOSITORY_OWNER" "cedws" }}'
      token: "{{ .Env.HOMEBREW_TAP_PUSH_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/{{ .ProjectName }}"]
          end

changelog:
  use: github
